apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: smart-interviewer
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_DB: "smart_interviewer"
  DATABASE_URL: "postgresql://postgres:123456@db-service:5432/smart_interviewer"
  SECRET_KEY: "896690fe24b40eefab845f30d2619676bf69d8daa32b44829a132b3a1dc916ca"
